//! The Part 27-F AN Shell built-in execution core and result model.
//!
//! This module extends the very end of the current language-core pipeline:
//!
//! ```text
//! BuiltinCommand
//!     ↓
//! execute_builtin(command)
//!     ↓
//! ExecutionResult
//! ```
//!
//! Execution owns execution behaviour only. It does NOT lex, parse or
//! re-recognise commands: it accepts [`BuiltinCommand`] values that the
//! semantic layer already validated, and runs their deterministic in-memory
//! semantics (`help`, `about`, `clear`, `echo`). Each crate stage's ownership
//! boundary is documented in `lib.rs`; this module never crosses back into an
//! earlier stage.
//!
//! Strict boundary
//! ---------------
//! This is not a shell, not a process launcher, not a terminal emulator and
//! not a Linux runtime. It never spawns, forks, execs, opens a PTY, reaches
//! JNI/Kotlin, reads or writes files, touches the network, mutates the
//! environment or any global state, and it never prints. The only observable
//! output a built-in can produce is the [`ExecutionResult`] it returns; the
//! caller decides how to render it.
//!
//! Infallibility
//! -------------
//! `execute_builtin` is deliberately infallible: no `Result`, no
//! `ExecutionError`. All four supported built-ins are pure, deterministic,
//! in-memory operations with no reachable failure -- help/about emit fixed
//! text, clear reports a request flag, and echo joins already-interpreted
//! argument values. Unknown commands never reach execution (semantic analysis
//! rejects them first), so execution has no unknown-command case to report.
//! Adding an error type here would only fabricate an unreachable failure, so
//! this milestone chooses the smallest honest API instead.
//!
//! Output ownership
//! ----------------
//! The AN Shell core (this crate) is the sole and authoritative owner of the
//! `help` and `about` text: the [`HELP_TEXT`] / [`ABOUT_TEXT`] constants below
//! are the definitive user-visible strings, emitted verbatim as one output unit
//! and rendered unchanged by the Android bridge. There is no Kotlin or frontend
//! executor to mirror. `echo` joins the already-interpreted [`Argument`] values
//! with a single space; see [`execute_builtin`] for the documented details.

use crate::ast::Argument;
use crate::semantic::{BuiltinCommand, BuiltinCommandKind};

/// The `help` output: the authoritative user-visible help text for the AN Shell
/// core built-ins. One output unit; the text contains embedded newlines and one
/// blank line, and the Android bridge renders it verbatim.
const HELP_TEXT: &str = concat!(
    "AliasNull Shell - built-in commands\n",
    "\n",
    "Available commands:\n",
    "help       Show this help text\n",
    "about      About AliasNull\n",
    "clear      Clear the terminal history\n",
    "echo ...   Print the given text back\n",
    "\n",
    "These commands are executed by the packaged AN Shell core. A Linux\n",
    "process runtime is not connected yet."
);

/// The `about` output: the authoritative user-visible about text for the AN
/// Shell core. It is capability-honest: it describes what the packaged core
/// executes today and states plainly what does not exist yet, without claiming
/// any Linux/process/PTY/filesystem capability.
const ABOUT_TEXT: &str = concat!(
    "AliasNull\n",
    "Mobile terminal · Native runtime · Linux environment\n",
    "\n",
    "This shell executes the AN Shell built-in commands (help, about,\n",
    "clear, echo) through the packaged language core. A Linux process\n",
    "runtime, filesystem and package manager are not implemented yet."
);

/// The in-memory result of executing one built-in command.
///
/// This is data, not a rendering and not a terminal interaction. It is
/// deterministic, dependency-free and free of Android-specific types, and it
/// carries no source spans. The caller decides how to display it later.
///
/// Representation
/// --------------
/// [`ExecutionResult::output`] holds the emitted output units, and
/// [`ExecutionResult::clear_requested`] records whether the command asked for
/// a terminal clear. `clear` is never faked with ANSI or control sequences:
/// the core only reports the requested action.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ExecutionResult {
    /// Zero or more emitted output units, in order.
    ///
    /// Each unit is the exact text one built-in emission produced -- the same
    /// payload the Android bridge renders as one `Output` event -- so a unit
    /// may contain embedded newlines, and blank lines are preserved as empty
    /// content inside a unit. `help` and `about` emit exactly one unit each,
    /// `echo` emits at most one, and `clear` emits none.
    pub output: Vec<String>,
    /// Whether the executed command requested a terminal clear.
    ///
    /// Only `clear` sets this to true; every other built-in leaves it false.
    /// No control sequence is ever generated by this core.
    pub clear_requested: bool,
}

/// Executes one already-recognised built-in command, deterministically.
///
/// The command must come from semantic analysis (or an equivalent
/// construction); execution does not re-check that the name is a built-in.
///
/// Per-command behaviour:
///
/// * `help`  -> one output unit: [`HELP_TEXT`].
/// * `about` -> one output unit: [`ABOUT_TEXT`].
/// * `clear` -> no output units; `clear_requested == true`.
/// * `echo`  -> one output unit when the command has arguments, else none.
///   Arguments are consumed from `command.arguments` as already-interpreted
///   [`Argument`] values and joined with a single ASCII space, in source
///   order, mixed Word/String kinds preserving their values. Quotes were
///   already removed by the lexer, so a quoted argument echoes without its
///   quote characters.
///
/// `help`, `about` and `clear` ignore any arguments that follow the name; only
/// `echo` consumes its arguments.
///
/// Echo semantics (deliberate)
/// ---------------------------
/// For ordinary single-space input (`echo hello world`) the joined value is
/// exactly the source words. Two properties follow from operating on
/// interpreted [`Argument`] values rather than raw source text (this crate's
/// fixed boundary), and are intentional, not silent text invention:
///
/// * quotes are stripped from quoted arguments (the lexer already removed
///   them), and
/// * runs of separator whitespace collapse to a single space, because the
///   lexer already turned them into token boundaries.
///
/// `help` and `about` output their constants verbatim.
pub fn execute_builtin(command: &BuiltinCommand) -> ExecutionResult {
    match command.kind {
        BuiltinCommandKind::Help => ExecutionResult {
            output: vec![HELP_TEXT.to_owned()],
            clear_requested: false,
        },
        BuiltinCommandKind::About => ExecutionResult {
            output: vec![ABOUT_TEXT.to_owned()],
            clear_requested: false,
        },
        BuiltinCommandKind::Clear => ExecutionResult {
            output: Vec::new(),
            clear_requested: true,
        },
        BuiltinCommandKind::Echo => {
            let mut output = Vec::new();
            if !command.arguments.is_empty() {
                output.push(join_arguments(&command.arguments));
            }
            ExecutionResult { output, clear_requested: false }
        }
    }
}

/// Joins interpreted argument values into one output unit with single spaces.
///
/// Reads only the values via [`Argument::value`]; it never re-scans source,
/// never re-parses quotes and never reconstructs whitespace the lexer already
/// discarded. Private: output formatting is an execution concern.
fn join_arguments(arguments: &[Argument]) -> String {
    let mut joined = String::new();
    for (index, argument) in arguments.iter().enumerate() {
        if index > 0 {
            joined.push(' ');
        }
        joined.push_str(argument.value());
    }
    joined
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::lex;
    use crate::parser::parse;
    use crate::semantic::{analyze, SemanticErrorKind, SemanticProgram};
    use crate::source::SourceText;

    /// Runs the real lex -> parse -> analyze pipeline over `source`, requiring
    /// full success (no lexer/parser/semantic error). Test-only.
    fn analyze_source(source: &str) -> SemanticProgram {
        let tokens = lex(&SourceText::new(source)).expect("lexer accepted this input");
        let program = parse(&tokens).expect("parser accepted this input");
        analyze(&program).expect("semantic analysis accepted this input")
    }

    /// Executes every built-in in `source` through the real pipeline.
    fn execute_all(source: &str) -> Vec<ExecutionResult> {
        analyze_source(source)
            .commands
            .iter()
            .map(execute_builtin)
            .collect()
    }

    /// Executes a source containing exactly one command.
    fn execute_one(source: &str) -> ExecutionResult {
        let mut results = execute_all(source);
        assert_eq!(results.len(), 1, "expected exactly one command in {source:?}");
        results.remove(0)
    }

    /// The semantic-error kind for a source that must be rejected before
    /// execution can ever run.
    fn rejection(source: &str) -> SemanticErrorKind {
        let tokens = lex(&SourceText::new(source)).expect("lexer accepted this input");
        let program = parse(&tokens).expect("parser accepted this input");
        analyze(&program).expect_err("semantic analysis must reject this input").kind
    }

    #[test]
    fn help_executes_successfully() {
        let result = execute_one("help");
        assert_eq!(result.output.len(), 1);
        assert!(!result.clear_requested);
    }

    #[test]
    fn help_output_matches_the_authoritative_help_text() {
        let result = execute_one("help");
        // HELP_TEXT is the AN Shell core's authoritative help text; the output
        // unit reproduces it verbatim as one multi-line unit.
        assert_eq!(result.output, vec![HELP_TEXT.to_owned()]);
        assert!(result.output[0].contains('\n'));
    }

    #[test]
    fn help_ignores_stray_arguments() {
        let result = execute_one("help whatever");
        assert_eq!(result.output, vec![HELP_TEXT.to_owned()]);
        assert!(!result.clear_requested);
    }

    #[test]
    fn about_executes_successfully() {
        let result = execute_one("about");
        assert_eq!(result.output.len(), 1);
        assert!(!result.clear_requested);
    }

    #[test]
    fn about_output_is_authoritative_and_capability_honest() {
        let result = execute_one("about");
        assert_eq!(result.output, vec![ABOUT_TEXT.to_owned()]);
        // Capability honesty: the text says plainly that a Linux process
        // runtime, filesystem and package manager are not implemented yet.
        assert!(result.output[0].contains("not implemented yet"));
        assert!(result.output[0].contains('\n'));
    }

    #[test]
    fn about_ignores_stray_arguments() {
        let result = execute_one("about now");
        assert_eq!(result.output, vec![ABOUT_TEXT.to_owned()]);
        assert!(!result.clear_requested);
    }

    #[test]
    fn clear_produces_no_ordinary_output() {
        let result = execute_one("clear");
        assert!(result.output.is_empty());
    }

    #[test]
    fn clear_requests_clear_requested() {
        let result = execute_one("clear");
        assert!(result.clear_requested);
    }

    #[test]
    fn clear_never_emits_control_sequences() {
        // The clear action is a boolean flag, never faked terminal output.
        let result = execute_one("clear");
        assert!(result.output.is_empty());
        assert!(result.clear_requested);
    }

    #[test]
    fn clear_ignores_stray_arguments() {
        let result = execute_one("clear now");
        assert!(result.output.is_empty());
        assert!(result.clear_requested);
    }

    #[test]
    fn echo_with_one_argument_preserves_the_argument() {
        let result = execute_one("echo hello");
        assert_eq!(result.output, vec!["hello".to_owned()]);
        assert!(!result.clear_requested);
    }

    #[test]
    fn echo_with_multiple_words_preserves_order_and_case() {
        let result = execute_one("echo Zed Alpha Mike");
        assert_eq!(result.output, vec!["Zed Alpha Mike".to_owned()]);
    }

    #[test]
    fn echo_joins_arguments_with_single_spaces() {
        let result = execute_one("echo one two three");
        assert_eq!(result.output, vec!["one two three".to_owned()]);
        assert_eq!(result.output[0].split(' ').count(), 3);
    }

    #[test]
    fn echo_quoted_argument_uses_interpreted_value_without_quotes() {
        let result = execute_one("echo \"hello world\"");
        assert_eq!(result.output, vec!["hello world".to_owned()]);
        // Quotes are gone; the value is the lexer's interpreted content.
        assert!(!result.output[0].contains('"'));
    }

    #[test]
    fn echo_mixed_argument_kinds_preserve_values_and_order() {
        let result = execute_one("echo one \"two words\" three");
        assert_eq!(result.output, vec!["one two words three".to_owned()]);
    }

    #[test]
    fn echo_with_no_arguments_produces_no_output() {
        for source in ["echo", "echo   "] {
            let result = execute_one(source);
            assert!(result.output.is_empty(), "expected no output for {source:?}");
            assert!(!result.clear_requested);
        }
    }

    #[test]
    fn echo_of_an_empty_quoted_argument_is_one_empty_output_unit() {
        // One argument exists (an empty interpreted string), so echo emits one
        // (empty) unit -- distinct from the no-arguments case above.
        let result = execute_one("echo \"\"");
        assert_eq!(result.output.len(), 1);
        assert_eq!(result.output[0], "");
        assert!(!result.clear_requested);
    }

    #[test]
    fn case_insensitive_echo_resolves_through_the_full_pipeline() {
        let program = analyze_source("ECHO hello");
        assert_eq!(program.commands[0].kind, BuiltinCommandKind::Echo);
        let result = execute_builtin(&program.commands[0]);
        assert_eq!(result.output, vec!["hello".to_owned()]);
    }

    #[test]
    fn multi_command_results_are_independent_and_stateless() {
        let results = execute_all("echo one\necho two");
        assert_eq!(results.len(), 2);
        assert_eq!(results[0].output, vec!["one".to_owned()]);
        assert_eq!(results[1].output, vec!["two".to_owned()]);
        assert!(!results[0].clear_requested);
        assert!(!results[1].clear_requested);
    }

    #[test]
    fn clear_does_not_leak_into_a_later_command_result() {
        let results = execute_all("clear\necho hi");
        assert_eq!(results.len(), 2);
        // First result is the independent clear request...
        assert!(results[0].clear_requested);
        assert!(results[0].output.is_empty());
        // ...and the later echo result is NOT implicitly cleared: it still
        // carries its own output and its own (false) clear flag.
        assert_eq!(results[1].output, vec!["hi".to_owned()]);
        assert!(!results[1].clear_requested);
    }

    #[test]
    fn unknown_command_is_rejected_before_execution() {
        // "foobar" is rejected by semantic analysis; there is no BuiltinCommand
        // for execution to receive, and execution exposes no raw-text entry.
        assert_eq!(rejection("foobar"), SemanticErrorKind::UnknownCommand);
    }

    #[test]
    fn quoted_command_name_is_rejected_before_execution() {
        assert_eq!(rejection("\"echo\" hello"), SemanticErrorKind::UnknownCommand);
    }

    #[test]
    fn execution_does_not_mutate_arguments_or_spans() {
        let program = analyze_source("echo one \"two words\" three");
        let command = &program.commands[0];
        let snapshot = command.clone();
        let _ = execute_builtin(command);
        // execute_builtin borrows; the command is unchanged in every field,
        // including each argument's value and source span.
        assert_eq!(*command, snapshot);
    }

    #[test]
    fn repeated_execution_of_the_same_command_is_equal() {
        let program = analyze_source("echo alpha beta");
        let command = &program.commands[0];
        let first = execute_builtin(command);
        let second = execute_builtin(command);
        assert_eq!(first, second);

        // Equal results also hold across an independent analysis of equal text.
        let again = analyze_source("echo alpha beta");
        let third = execute_builtin(&again.commands[0]);
        assert_eq!(first, third);
    }
}
